// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQM2ZQEPKt_GjOCd0TCwFivSP5_uhSg6c',
    appId: '1:339477941630:web:d62f17ff7c4c0abaf2b72f',
    messagingSenderId: '339477941630',
    projectId: 'rlinkers-bc0eb',
    authDomain: 'rlinkers-bc0eb.firebaseapp.com',
    databaseURL: 'https://rlinkers-bc0eb-default-rtdb.firebaseio.com',
    storageBucket: 'rlinkers-bc0eb.appspot.com',
    measurementId: 'G-MFT7VT672V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztZDy1bTaBk-_Llm-XrWe4UXJsw00XO4',
    appId: '1:339477941630:android:dd727534f13cfa70f2b72f',
    messagingSenderId: '339477941630',
    projectId: 'rlinkers-bc0eb',
    databaseURL: 'https://rlinkers-bc0eb-default-rtdb.firebaseio.com',
    storageBucket: 'rlinkers-bc0eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBke7vhiNRGApYPNTxQ4wMZsvCy781cxqg',
    appId: '1:339477941630:ios:2ca4485e9c40d73af2b72f',
    messagingSenderId: '339477941630',
    projectId: 'rlinkers-bc0eb',
    databaseURL: 'https://rlinkers-bc0eb-default-rtdb.firebaseio.com',
    storageBucket: 'rlinkers-bc0eb.appspot.com',
    iosClientId: '339477941630-mq8pmpe22qnei352fbo01su5o9sq9dah.apps.googleusercontent.com',
    iosBundleId: 'com.example.rlinkers',
  );
}
